### ISSUE TITLE
Improved logging

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#265]
**Is your feature request related to a problem? Please describe.**
Currently, we have our own logging class, which is fine, but it doesn't provide the option to extended debugging or error-reporting.

**Describe the solution you'd like**
Something like [loguru](https://loguru.readthedocs.io/en/stable/overview.html) would be good to have. This gives more flexibility in logging, and provides more functionality related to tracing.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.](https://www.kdnuggets.com/2021/12/3-tools-track-visualize-execution-python-code.html)

**Additional context**
N.A.

**Comment by sarthakpati** [comment]
Another option: https://neptune.ai/product#how-it-works

**Comment by meghbhalerao** [comment]
I recently came across `wandb` which is free and seems to be good for hyperparamter sweeps and visualization in general - https://wandb.ai/site.

**Comment by AlexanderGetka-cbica** [comment]
Agreed that the built-in logging module is best for this. I can handle that work. This will mean that we will need to start requesting changes PRs with plain print statements.
Loguru and snoop are cool, but my hunch is that with the type of code we are writing, it will most likely only print out python object notations like"<numpy.array at 0xdeadbeefbadbabe>".

Can I ask what the intended user workflow is to visualize hyperparameter tuning? Do we expect this to be part of "gandlf_collectStats", (i.e., done post-hoc after a training is performed)? Or is this something we want to be generating/visualizing while training is running?
