### ISSUE TITLE
Add option to handle large WSI images during inference

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#471]
**Is your feature request related to a problem? Please describe.**
Currently, large WSIs (i.e., of size `~[100k x 150k]`) simply cannot be processed using a "normal" amount of hardware resources, and the process completely fails.

**Describe the solution you'd like**
Fall back to not initialize multiple high-memory variables (such as the tissue mask and probability maps) and just write the predictions. This is obviously going to be useless for segmentation, but at least the error messages will be meaningful with an attached subject ID instead of an outright failure.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by Geeks-Sid** [comment]
This looks good.
