### ISSUE TITLE
Using deterministic algorithms

### ISSUE THREAD

**Issue by sylwiamm** [mlcommons/GaNDLF#515]
**Is your feature request related to a problem? Please describe.**
Some experiments require reproducibility which is currently not supported.

**Describe the solution you'd like**
I would like to ensure reproducible results of training and inference.

**Describe alternatives you've considered**
NA

**Additional context**
https://pytorch.org/docs/stable/notes/randomness.html#reproducibility

**Comment by AlexanderGetka-cbica** [comment]
Hi @avantGardenerCodes, Sarthak mentioned to me that you are currently working on this -- if so, can I assign this issue to you?
