### ISSUE TITLE
Add another optimizer (or 2) as option

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#586]
**Is your feature request related to a problem? Please describe.**
Currently, GaNDLF only offers Adam and SGD as options for optimizers, which could sometimes be a bit limiting.

**Describe the solution you'd like**
Add ~[RMSProp](https://pytorch.org/docs/stable/generated/torch.optim.RMSprop.html#torch.optim.RMSprop), and optionally~ one or more of the following:
- [LBFGS](https://pytorch.org/docs/1.13/generated/torch.optim.LBFGS.html#torch.optim.LBFGS) 
- [RAdam](https://pytorch.org/docs/1.13/generated/torch.optim.RAdam.html#torch.optim.RAdam)
- ~[Rprop](https://pytorch.org/docs/1.11/generated/torch.optim.Rprop.html#torch.optim.Rprop)~
- ~[ASGD](https://pytorch.org/docs/1.11/generated/torch.optim.ASGD.html#torch.optim.ASGD)~

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

EDIT [2023/03/20]: updated to the optimizers that are actually missing.

**Comment by Geeks-Sid** [comment]
@sarthakpati , Unless I am mistaken from looking at LOC from the [file](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/optimizers/wrap_torch.py), we are supporting `SGD, ASGD, Rprop, Adam, AdamW, Adamax, Adadelta, Adagrad, RMSprop`. Also, any specific reason why we need [LBFGS](https://pytorch.org/docs/1.11/generated/torch.optim.LBFGS.html#torch.optim.LBFGS) or is it just an enhancement?

**Comment by Geeks-Sid** [comment]
Yeah, sounds good. He could try adding all the [ones](https://pytorch.org/docs/1.11/optim.html#algorithms) (LBFGS, RAdam) that are not added in GaNDLF as a part of the practice. :)

**Comment by AdiSir05** [comment]
That sounds good to me! I can start with LBFGS and RAdam. If there are more optimizers to add, I can do those after.
