### ISSUE TITLE
Convert main scripts to console entry points

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#610]
**Is your feature request related to a problem? Please describe.**
Currently, GaNDLF's main interactive components are based on standalone scripts, which are an older way of defining python packages.

**Describe the solution you'd like**
Converting them to dedicated functions with console entry points would be better (a good read on why is [here](https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py)), and more compatible with future changes in python.

**Describe alternatives you've considered**
N.A.

**Additional context**
More details in: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

**Comment by sunny1401** [comment]
@sarthakpati  - Can i take this issue up? I have already signed the form for github participation and I am in the working group

**Comment by sunny1401** [comment]
@sarthakpati - I have finished going through the file structure etc.. I have one question - for example for GaNDLF.anonymize - I found [this file](https://github.com/mlcommons/GaNDLF/blob/master/gandlf_anonymizer). Is the intent of this ticket to just move/copy this code to command_line.py within [anonymize/](https://github.com/mlcommons/GaNDLF/tree/master/GANDLF/anonymize) and update the setup.py as
entry_points={
            "console_scripts": ["gandlf_anonymizer=GANDLF.anonymize:.console.main"]
}

and then do this for all the interactive components. I have something for PR but I want to make sure I am on the right track before raising a PR

**Comment by sarthakpati** [comment]
Fixed in #818
