### ISSUE TITLE
Possibly update version management

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#650]
**Is your feature request related to a problem? Please describe.**
Building off the discussion in #648, it might be a good idea to have a discussion about version management.

**Describe the solution you'd like**
Possible options (will be updated as and when more come in via comments):
- Versioneer [[ref](https://github.com/python-poetry/poetry)] - https://pypi.org/project/versioneer/
- commitizen - https://github.com/commitizen-tools/commitizen
- poetry [[ref](https://stackoverflow.com/questions/57628064/automating-python-package-release-process#:~:text=6%20remain%20manual.-,Package%20management,-I%27ll%20use%20poetry)] - https://github.com/python-poetry/poetry
- bump [[ref](https://github.com/di/bump)] - straightforward version bumps, but not actively maintained
- setuptools_scm [[ref](https://github.com/pypa/setuptools_scm/)] - seems like the great-grand-daddy of them all
- incremental [[ref](https://github.com/twisted/incremental#updating)] - seems to be a simpler form of `setuptools_scm`, and does support auto-versioning with dev/rc support

**Describe alternatives you've considered**
I am sure there are others, and any insight from the community would be very helpful!

**Additional context**
Need a better way to manage versions than manually adding/removing `-dev` to `version.py`.

**Comment by AlexanderGetka-cbica** [comment]
Agreed. Poetry is pretty popular but also means that we need to alter how we do dependencies, need to make sure people check in poetry.lock, and so on. Not sure if there will be any issues because we already have a repo (rather than starting *with* poetry).
This will also change our CI/CD for publishing. Anyway, self-assigning.

**Comment by sarthakpati** [comment]
Just want to add this for notes: https://github.com/astral-sh/uv
