### ISSUE TITLE
Test coverage for `entrypoint` variable of mlcube deployment

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#733]
> @hasan7n: is there a way we can check this in the tests? We should perhaps discuss this in a separate issue, since this could perhaps be important.

_Originally posted by @sarthakpati in https://github.com/mlcommons/GaNDLF/pull/730#discussion_r1391299090_

**Comment by sarthakpati** [comment]
@VukW this should be fixed already with the new API branch, right?

**Comment by VukW** [comment]
@sarthakpati No, this part was never touched in new API branch. To tell truth I don't get quite well even after reading parent PR what exactly is the issue about? What do we need to check?

**Comment by sarthakpati** [comment]
Ah okay. It is basically that these lines are not getting covered by tests:

![image](https://github.com/mlcommons/GaNDLF/assets/11719673/f1080f71-c577-4431-9a15-aefd77887275)

And since this is (IMO) an integral part of the deploy mechanism, I would assume a test would need to updated/added to cover it. I was trying to ask clarification from @hasan7n but he hasn't responded this thread, yet.

**Comment by VukW** [comment]
Are you talking about just a coverage of this line in `deploy.py`, or also about real check if container built with such an entrypoint would run properly?

**Comment by sarthakpati** [comment]
The coverage.

**Comment by sarthakpati** [comment]
@hasan7n - based on conversation about the metrics mlcube, do you think you could take care of this as well?
