### ISSUE TITLE
Add an option for backwards compatibility for `parseConfig`

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#790]
**Is your feature request related to a problem? Please describe.**
Once #783 was resolved, `parseConfig` was renamed, but this causes issues with backward compatibility (https://github.com/securefederatedai/openfl/pull/920).

**Describe the solution you'd like**
Add a new submodule to ensure backwards compatibility.

**Describe alternatives you've considered**
N.A.

**Additional context**
The PR for OpenFL still needs to be merged.

**Comment by scap3yvt** [comment]
Happy to take this on.
