### ISSUE TITLE
Step function could use a refactor as it is currently bloated and hard to read and debug

### ISSUE THREAD

**Issue by Geeks-Sid** [mlcommons/GaNDLF#792]
**Is your feature request related to a problem? Please describe.**
Step function could use a refactor as it is currently bloated and hard to read and debug. Some functions could be refactored and stashed in utils

**Describe the solution you'd like**
Refactor code and Move function to utils

**Describe alternatives you've considered**

**Additional context**

**Comment by sarthakpati** [comment]
@Geeks-Sid - are you still working on this?
