### ISSUE TITLE
Some code styling through Ruff for linting

### ISSUE THREAD

**Issue by Geeks-Sid** [mlcommons/GaNDLF#794]
**Is your feature request related to a problem? Please describe.**
Currently, there is a need for robust linting capabilities within the development environment to ensure code quality and adherence to coding standards. While existing linters offer some level of support, there is a gap in the availability of a comprehensive and efficient Python linter specifically designed for detecting potential security vulnerabilities and bugs.

**Describe the solution you'd like**
I propose integrating [Ruff](https://github.com/astral-sh/ruff), a powerful Python linter, into the development environment. Ruff is specifically designed to analyze Python code for common security vulnerabilities, performance issues, and coding errors. By incorporating Ruff, developers can benefit from real-time feedback and suggestions to improve code quality and mitigate potential risks.

**Describe alternatives you've considered**

**Additional context**
Integrating Ruff into the development environment would streamline the code review process and enhance the overall security posture of the GaNDLF. Additionally, Ruff's extensibility allows for customization to suit specific project requirements. A seamless integration of Ruff would empower developers to write more secure and reliable Python code.

**Comment by sarthakpati** [comment]
@Geeks-Sid - are you still planning to put this in?

**Comment by sarthakpati** [comment]
> Do you think we should allow bots write permissions to PR? 

I don't think giving it write access is a good idea. However, having this as a check could potentially be of benefit. I am not very familiar with ruff, though. Can you give a high-level overview?

**Comment by sarthakpati** [comment]
> Let's consider giving Ruff a try to enhance our code quality and development speed.

I don't have any issue with using any linter as long as we are able to put together a CI checker and an easy way to use this for developers.

Any comments from your end, @VukW, @szmazurek?
