### ISSUE TITLE
Fix some code style issues reported by codacy 

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#800]
**Is your feature request related to a problem? Please describe.**
Codacy has reported a few issues to fix that relate to the code style: https://app.codacy.com/gh/mlcommons/GaNDLF/issues/current?levels=Warning&categories=CodeStyle

**Describe the solution you'd like**
Fixing this should improve readability.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by benmalef** [comment]
Hi @sarthakpati can you please assign this issue to me.
