### ISSUE TITLE
Memory build-up on various locations

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/GaNDLF#806]
When using the FeTS tool ([script](https://github.com/aristizabal95/FeTS-AI-Front-End/blob/1ef893952116690dfe49a6262622b1a07b31220e/src/applications/PrepareDataset.py)), we noticed two sources of memory build-up:
1. Memory build-up due to figure_generator ([lines](https://github.com/aristizabal95/FeTS-AI-Front-End/blob/1ef893952116690dfe49a6262622b1a07b31220e/src/applications/PrepareDataset.py#L145-L152)), around 200MB per call.
2. Memory build-up due to GaNDLF's `main_run` function ([lines](https://github.com/aristizabal95/FeTS-AI-Front-End/blob/1ef893952116690dfe49a6262622b1a07b31220e/src/applications/PrepareDataset.py#L333-L342)), around 400MB per call.

Further profiling of GaNDLF'S `main_run` showed the information below (note: the profiling was done on GaNDLF's commit `616b37bafad8f89d5c816a88f44fa30470601311`)
- Around 100MB build-up caused by [this line](https://github.com/mlcommons/GaNDLF/blob/616b37bafad8f89d5c816a88f44fa30470601311/GANDLF/compute/inference_loop.py#L67-L74). Note that clearing the `model` variable at the end of the inference loop **will** resolve this.
- Around 280MB build-up caused by [this line](https://github.com/mlcommons/GaNDLF/blob/616b37bafad8f89d5c816a88f44fa30470601311/GANDLF/utils/modelio.py#L239). Note that clearing the `compiled_model` variable **will not** resolve this, which suggests that the build-up happens inside the compiled ov library.
- Other multiple lines of code in different places cause few MBs build-ups

**Comment by hasan7n** [comment]
FWIW, this is the memory profiler used:

**Comment by sarthakpati** [comment]
> i can tackle this issue

Thanks! I am assuming that this will relate to #780 as well.
