### ISSUE TITLE
[FEATURE] Set `line-length` for `black` in the `project.toml` file

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#819]
### Is your feature request related to a problem? Please describe.
`black` can behave differently based on each developer's environment, which can create formatting issues [[ref](https://github.com/szmazurek/GaNDLF/pull/31#pullrequestreview-1941539508)].

### Describe the solution you'd like
Let's try to standardize some of the linting behavior, starting with `line-length`.

### Describe alternatives you've considered
N.A.

### Additional context
N.A.

**Comment by scap3yvt** [comment]
Happy to take this on.
