### ISSUE TITLE
[FEATURE] Add the ability to generate training/validation/testing CSV with proportional splits

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#829]
### Is your feature request related to a problem? Please describe.
Currently, the splits getting generated as _purely_ based on k-fold cross validation [[ref](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/training_manager.py#L73)], which is fine for segmentation/regression/synthesis, but does not give appropriate results for classification.

### Describe the solution you'd like
Add the ability to perform [**stratified** k-fold](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html) prior to performing training.

### Describe alternatives you've considered
N.A.

### Additional context
N.A.

**Comment by scap3yvt** [comment]
Please assign to me.
