### ISSUE TITLE
[BUG] Moving from version `0.0.XX` to `0.Y.0` creates compatibility issues.

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#840]
### Describe the bug
When the new CLI is ready (#818), we will transition to version `0.1.0`. However, this is creating issues with the [`version_check`](https://github.com/mlcommons/GaNDLF/blob/2b2445cba24e98b3dd51dd6645324ed5d5cd2769/GANDLF/utils/generic.py#L106) function.

### To Reproduce
1. Put min/max version in the config as `0.0.XX` and `0.1.0`.
2. Run any training command.
3. See version compatibility error.

### Expected behavior
Clearly, `0.1.0` is greater than `0.0.XX`. However, the custom [`version_check`](https://github.com/mlcommons/GaNDLF/blob/2b2445cba24e98b3dd51dd6645324ed5d5cd2769/GANDLF/utils/generic.py#L106)  cannot seem to comprehend this.

### Media
N.A.

### Environment information

```
GANDLF version: 0.0.20-dev
Git hash: 3c61892f9d5ffc9d17720ccfd413c1b23cfd50f0
Platform: Windows-10-10.0.22631-SP0
Machine: AMD64
Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
Architecture: 64bit WindowsPE
Python environment:
  Version: 3.11.6
  Implementation: CPython
  Compiler: MSC v.1935 64 bit (AMD64)
  Build: main Oct  3 2023 10:29:11
```

### Additional context
N.A.

**Comment by scap3yvt** [comment]
Please assign this to me.

**Comment by scap3yvt** [comment]
I believe using [`Packaging`](https://packaging.pypa.io/en/latest/version.html#packaging.version.parse) would be a good solution:

```python
>>> from packaging.version import Version
>>> v1 = Version("0.0.19") 
>>> v2 = Version("0.1.0")
>>> v1 > v2
False
```

This will ensure that we don't have to maintain any custom code. Additionally, if we move to a more formal release schedule (with Alpha/Beta/Gamma/RC versions), we won't need to make any further edits, since this is already covered:

```python
>>> from packaging.version import Version
>>> v1 = Version("0.2.0-Alpha")
>>> v2 = Version("0.2.0-RC")   
>>> v1 > v2 
False
>>> v1 = Version("0.2.0-Alpha5") 
>>> v1 > v2
False
```
