### ISSUE TITLE
[BUG] Loss signatures: CE Loss failure because of additional `params` argument

### ISSUE THREAD

**Issue by VukW** [mlcommons/GaNDLF#854]
### Describe the bug
During [loss computations](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/compute/loss_and_metric.py#L113)
 it is assumed that loss function takes three params: prediction, target, params. However, it's not true for [CE](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/losses/regression.py#L59) loss that takes only prediction and target, so using `loss_function: ce` fails.
 
### To Reproduce
try to train any model with `loss_function: ce`

### Media
If applicable, add images, screenshots or other relevant media to help explain your problem.

### Environment information

GaNDLF version, OS, and any other relevant information.

### Additional context
The straightforward solution is just to add an unused `params` arg to CE function.  However, I believe, doing this would cause linter / codacy failures as parameter is defined but not used. In this case the best option IMO is to create a standard class interface for losses:

```python
## different file, so that this can be used by segmentation, classification, regression, and compound/hybrid losses

class LossFunctionInterface(ABC):
    @staticmethod
    @abstractmethod
    def compute_loss(
        self, targets: torch.Tensor, predictions: torch.Tensor, params: dict
    ):
        """
        Abstract method to compute the loss function.

        Args:
            targets (torch.Tensor): The target values.
            predictions (torch.Tensor): The predicted values.
            params (dict): The parameters.

        Raises:
            NotImplementedError: This method must be implemented in the derived class.
        """
        raise NotImplementedError

class DCCE(LossInterface):
    @staticmethod
    def compute_loss(predictions: torch.Tensor, targets: torch.Tensor, params: dict) -> torch.Tensor:
        ### ... move DCCE calculation logic there...

# in loss_and_metric.py it can be used as:
# loss_function.calc(predictions, targets, params)
```
and the same with all other losses. In this case all the losses would have the same signature and can be used interchangeably. If signature of any loss function differs, both Codacy and IDE would warn developer that something goes wrong.

**Comment by sarthakpati** [comment]
The solution makes complete sense to me. We should do this for all the losses, not just ce. And on that note, perhaps `ce` is a bit ambiguous, and we should make it explicit: either `CEL` (i.e., [cross entropy loss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#crossentropyloss)), `BCEL` (i.e., [binary cross entropy loss](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html#bceloss)), or `BCEL_logits` (i.e., [binary cross entropy with logits](https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html)). 

Thoughts?
