### ISSUE TITLE
[FEATURE] Update to new docker-py dependency once released

### ISSUE THREAD

**Issue by VukW** [mlcommons/GaNDLF#872]
Currently (on 2024-05-24) the latest version of `docker` python package is 7.0.0.
However, acouple of days ago new `requests` library was released, `2.32.0`.
`docker` package [is not compatible](https://github.com/docker/docker-py/issues/3256) right now with new `requests` version, so we downgraded https://github.com/mlcommons/GaNDLF/pull/871 `requests` depencency to `2.31.0`.

What to do: once new `docker` [version released](https://pypi.org/project/docker/) (I velieve it should be like `7.0.1`) , remove dependency restriction on `requests` and update `requests` to `2.32.0`

**Comment by sarthakpati** [comment]
@VukW the new docker version is up. I think could potentially tie in well with #875, but needs to go in as a separate PR. @benmalef do you want to take this on as well?

**Comment by benmalef** [comment]
@sarthakpati yes I can take a look.

**Comment by benmalef** [comment]
Hi guys @VukW , @sarthakpati 

I have tried to update the `requests` version to ` 2.32.0` and the ` docker `version to `7.1.0`.
But, this error has been raised. 

![image](https://github.com/user-attachments/assets/c36a3ea8-bdfb-42ed-bb9b-d99f7b786c8f)

I open this PR:
https://github.com/benmalef/GaNDLF/pull/22#issue-2511309320

**Comment by sarthakpati** [comment]
I don't have any detailed insight apart from what's posted on https://github.com/docker/docker-py/issues/3256

Perhaps @VukW can shed some light?
