### ISSUE TITLE
[FEATURE]  Add Docker Compose

### ISSUE THREAD

**Issue by benmalef** [mlcommons/GaNDLF#875]
### Is your feature request related to a problem? Please describe.
Now we use docker commands to run or build a container.  Would it be useful to use [Docker Compose](https://docs.docker.com/compose/) for managing them?

### Describe the solution you'd like
Compose simplifies the control of entire application stack, making it easy to manage services, networks, and volumes in a single, comprehensible YAML configuration file. Then, with a single command, you create and start all the services from a configuration file.

### Describe alternatives you've considered
N.A.
### Additional context
N.A.

**Comment by sarthakpati** [comment]
Thanks for the feature request! This makes sense to me, but since I am not at all a docker expert, I will also ask for input from @VukW, @szmazurek, @hasan7n and @aristizabal95 for this.

**Comment by sarthakpati** [comment]
@benmalef would you be interested in taking this on?

**Comment by benmalef** [comment]
@sarthakpati  yes of course..!!
