### ISSUE TITLE
Rescale transform does not properly use input parameters

### ISSUE THREAD

**Issue by szmazurek** [mlcommons/GaNDLF#907]
### Describe the bug
In the rescale_transform, RescaleIntensity object always uses only default parameters, even if user specifies custom ones. The reason for that is that during the initialization, RescaleIntensity parses the arguments and stores them as instance variables named differently than input args. For example, `out_min_max` is parsed and stored in the `self.out_min` and `self.out_max` variables. The function currently tries to assign user specified parameters to the fields that are not used when calling already initialized Rescaler object. 
The solution is to either replace proper instance variables, or simply use parameters unpacking in the constructor.
### To Reproduce
1. Use the 'rescale' transform and specify one of custom arguments, for example 'out_min_max' = [-1,1] in the config file
2. Observe the pixel intensities - they are still in the [0,1] range as parameters did not cause the object properties to change
### Expected behavior
Rescaler would incorporate specified custom parameters and process the data approprietly.

### Environment information

GaNDLF version, OS, and any other relevant information.
-
### Additional context
-

**Comment by sarthakpati** [comment]
Thanks, @szmazurek!

Are you working on the fix?

**Comment by szmazurek** [comment]
Just opened a PR for it

**Comment by sarthakpati** [comment]
Fixed with #908
