### ISSUE TITLE
[BUG] Logging is not flushing to console if `--log-file` is `None`

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#963]
### Describe the bug
If the `gandlf run` command is run with the `--log-file` parameter, the user expectation is that the logs would flush to console, which is not happening.

### To Reproduce
1. Run the `gandlf run` command for any job (training or inference) without the `--log-file` parameter.
2. The [`GANDLF.utils.logger_setup`](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/utils/gandlf_logging.py#L37) kicks in from [this line](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/entrypoints/run.py#L163).
3. See the logs trying to run using the temporary log from [here](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/utils/gandlf_logging.py#L10).
4. This is potentially problematic, since there are situations where the OS returns a location where a compute job (not the user, specifically) does not have write access, prompting users to see permission error.

### Expected behavior
If the ``log-file`` parameter is `None`, the logs should flush to console.

### Media
N.A.

### Environment information
<!-- Put the output of the following command:
N.A.

### Additional context
N.A.

**Comment by sarthakpati** [comment]
@benmalef I think we had discussed this before as well. Can you check?

**Comment by benmalef** [comment]
I test it on my pc. 

![image](https://github.com/user-attachments/assets/2a416fdd-a70b-4630-91bd-737534dbae6d)

![image](https://github.com/user-attachments/assets/c12cfecf-d9c5-41bd-8faa-3488789c9a35)

And the log file is created.
![image](https://github.com/user-attachments/assets/be66cf0e-3e66-4446-a7a9-91dc1a1a24bf)


If the gandlf run command is run with the --log-file parameter, the user should define the file path that they want to save the logs.
If the --log-file is not provided, the log file is saved in the tmp dir and we have decided to save it there because the user will have surely write access. 

We only flush into the console if an error has been raised. 
So, If we want to flush everything in the console, we should change the implementation.

**Comment by benmalef** [comment]
> > should only flush in the console. ??
> 
> Absolutely. We are already seeing at least one instance where the user does not have write access to the `/tmp/` folder.

Okay, I'll make the changes. All the output will be flushed to the console. :)  Thanks a lot for the update!

**Comment by benmalef** [comment]
> I think [this solution](https://stackoverflow.com/a/41915516) might be better than the `tempfile.gettempdir()` approach, which seems to work for both.
> 
> Windows:
> 
> ```powershell
> (base) PS C:\Projects\brats2020_convert_csv_to_tex> python -c "from pathlib import Path; print(str(Path.home()))"           
> C:\Users\sarth
> ```
> 
> And Linux:
> 
> ```shell
> (venv_conda_recipes) sarthakpati@cbica-bakas-pc0:/mnt/c/Users/sarth/Downloads$ python -c "from pathlib import Path; print(str(Path.home()))"
> /home/sarthakpati
> ```

Does it ensure the "write-access" privilege. ?

**Comment by benmalef** [comment]
Sorry, I am little confused. :P  @sarthakpati 
So, if the user doesn't use the --log-file, the logfile will be saved  in home/.gandlf/<timestamp>.log 
Or the logs will be flushed to console ??

**Comment by sarthakpati** [comment]
So, there are 3 options for the case where `log_file == None` [here](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/entrypoints/run.py#L163):

1. Flush to console (which I think is the correct behavior).
2. Write to a temporary file using details from [this comment](https://github.com/mlcommons/GaNDLF/issues/963#issuecomment-2460439404) and let the user know where the logs are getting written on the console.
3. (Preferred) Write the logs to a temp location using details from [this comment](https://github.com/mlcommons/GaNDLF/issues/963#issuecomment-2460439404) **only** when the user passes `"home"` or `"temp"` for the `--log-file` parameter. Otherwise, flush to console.

Thoughts?

**Comment by benmalef** [comment]
So, If the user doesn't provide the --log-file. 

-  The default is to flush the logs in the console. **But only the **Info logs** and the **error messages.****
- If they want more details (e.x Debug logs ), they can use --log-file
  1. the ```--log-file home ``` then the logs will be saved in the  **home/.gandlf/(timestamp).log** using Path.home()
  2. the ```--log-file temp``` then the logs will be saved in the  **temp/.gandlf/(timestamp).log** using tempfile.gettempdir()
  3. they can provide their own path for log file  ```--log-file <user-filename> ```

@sarthakpati

**Comment by sarthakpati** [comment]
Edited comment for clarity.

Here's what I think, and LMK what your thoughts are for the case where the user does not provide anything in the `--log-file` parameter:

- Flush only the `info` and `error` messages of the logs in the console. 
- Full logs go into `${home}/.gandlf/(timestamp).log` using `Path.home()`, and provide this path to the user when it gets initialized.

This allows us to ensure that we have a full snapshot of the logs, while (from the user side) there is an expected behavior of seeing things coming on the console.
