### ISSUE TITLE
Pytorch Conda dependencies might stop working

### ISSUE THREAD

**Issue by Geeks-Sid** [mlcommons/GaNDLF#969]
[Read more here](https://dev-discuss.pytorch.org/t/pytorch-deprecation-of-conda-nightly-builds/2590)

**Comment by sarthakpati** [comment]
Thanks for the post! 

It seems like PyTorch’s official Anaconda ([`-c pytorch`](https://anaconda.org/pytorch)) channel is getting deprecated. But we are using [pytorch from the conda-forge channel](https://anaconda.org/conda-forge/pytorch). Unless that dependency breaks, there is no concern for us. 

Closing this out.
